name = "JCH_Simulation"
uuid = "53005086-5384-4861-a53a-096895311029"
version = "0.1.0"
authors = ["Vedant Mahadik"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumCumulants = "35bcea6d-e19f-57db-af74-8011de6c7255"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[compat]
ModelingToolkit = "10.32.1"
OrdinaryDiffEq = "6.103.0"
QuantumCumulants = "0.4.2"
